{{- range .Values.volumesData}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.name}}
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  hostPath:
    path: {{.hostPath.path}}
    type: {{.hostPath.type}}
{{- end}}