apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.example.com
  labels:
    {{- include "terraform-serviceaccount-roles-and-permissions.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        {{- with .Values.usersCrdSchema }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
  scope: Cluster
  names:
    plural: users
    singular: user
    kind: User