apiVersion: usermanagement.github.com/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: user-sample1
spec:
  roleRules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - create
    - update
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - create
    - update
  userGroup: test
