apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "terraform-serviceaccount-roles-and-permissions.fullname" . }}
  labels:
    {{- include "terraform-serviceaccount-roles-and-permissions.labels" . | nindent 4 }}
{{- with .Values.clusterroleRules }}
rules:
{{- toYaml . | nindent 2 }}
{{- end }}