apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "terraform-serviceaccount-roles-and-permissions.fullname" . }}
  labels:
    {{- include "terraform-serviceaccount-roles-and-permissions.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "terraform-serviceaccount-roles-and-permissions.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "terraform-serviceaccount-roles-and-permissions.serviceAccountName" . }}
  namespace: default