apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform-serviceaccount-roles-and-permissions.fullname" . }}
  labels:
    {{- include "terraform-serviceaccount-roles-and-permissions.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "terraform-serviceaccount-roles-and-permissions.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "terraform-serviceaccount-roles-and-permissions.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "terraform-serviceaccount-roles-and-permissions.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: copy-files-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ['sh', '-c', 'cp /kubernetes-pki/* /tmp/kubernetes-pki/']
        volumeMounts:
        - name: volume-0
          mountPath: /tmp/kubernetes-pki
      containers:
      - name: {{ include "terraform-serviceaccount-roles-and-permissions.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        env:
        - name: TFVARS
          value: {{.Values.tfvarsLocation.dir}}/terraform.tfvars
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: terraform-tfvars
          mountPath: {{.Values.tfvarsLocation.dir}}
        {{- range .Values.volumesData}}
        - mountPath: {{.mountPath}}
          name: {{.name}}
        {{- end}}
      volumes:
      - name: terraform-tfvars
        configMap:
          name: terraform-tfvars
      {{- range .Values.volumesData}}
      - name: {{.name}}
        hostPath:
          path: {{.hostPath.path}}
          type: DirectoryOrCreate
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
